import { Element } from '@/lib/types/element'
import { Bond, BondType } from '@/lib/types/compound'

// Mock Elements
export const mockHydrogen: Element = {
  _id: 'h-id',
  id: 'H',
  atomicNumber: 1,
  symbol: 'H',
  name: 'Hydrogen',
  atomicMass: 1.008,
  category: 'nonmetal',
  group: 1,
  period: 1,
  block: 's',
  electronConfiguration: '1s1',
  electronsPerShell: [1],
  phase: 'gas',
  meltingPoint: 14.01,
  boilingPoint: 20.28,
  density: 0.00008988,
  electronegativity: 2.20,
  atomicRadius: 120,
  ionizationEnergy: 1312,
  oxidationStates: [-1, 1],
  valency: 1,
  maxBonds: 1,
  discoveredBy: 'Henry Cavendish',
  yearDiscovered: 1766,
  isRadioactive: false,
  halfLife: null,
  color: '#FFFFFF',
  summary: 'Hydrogen is the lightest element.',
}

export const mockOxygen: Element = {
  _id: 'o-id',
  id: 'O',
  atomicNumber: 8,
  symbol: 'O',
  name: 'Oxygen',
  atomicMass: 15.999,
  category: 'nonmetal',
  group: 16,
  period: 2,
  block: 'p',
  electronConfiguration: '1s2 2s2 2p4',
  electronsPerShell: [2, 6],
  phase: 'gas',
  meltingPoint: 54.36,
  boilingPoint: 90.20,
  density: 0.001429,
  electronegativity: 3.44,
  atomicRadius: 152,
  ionizationEnergy: 1313.9,
  oxidationStates: [-2, -1],
  valency: 2,
  maxBonds: 2,
  discoveredBy: 'Joseph Priestley',
  yearDiscovered: 1774,
  isRadioactive: false,
  halfLife: null,
  color: '#4ECDC4',
  summary: 'Oxygen is essential for respiration.',
}

export const mockCarbon: Element = {
  _id: 'c-id',
  id: 'C',
  atomicNumber: 6,
  symbol: 'C',
  name: 'Carbon',
  atomicMass: 12.011,
  category: 'nonmetal',
  group: 14,
  period: 2,
  block: 'p',
  electronConfiguration: '1s2 2s2 2p2',
  electronsPerShell: [2, 4],
  phase: 'solid',
  meltingPoint: 3823,
  boilingPoint: 4098,
  density: 2.267,
  electronegativity: 2.55,
  atomicRadius: 170,
  ionizationEnergy: 1086.5,
  oxidationStates: [-4, -3, -2, -1, 0, 1, 2, 3, 4],
  valency: 4,
  maxBonds: 4,
  discoveredBy: 'Ancient',
  yearDiscovered: null,
  isRadioactive: false,
  halfLife: null,
  color: '#4ECDC4',
  summary: 'Carbon is the basis of organic chemistry.',
}

export const mockNitrogen: Element = {
  _id: 'n-id',
  id: 'N',
  atomicNumber: 7,
  symbol: 'N',
  name: 'Nitrogen',
  atomicMass: 14.007,
  category: 'nonmetal',
  group: 15,
  period: 2,
  block: 'p',
  electronConfiguration: '1s2 2s2 2p3',
  electronsPerShell: [2, 5],
  phase: 'gas',
  meltingPoint: 63.15,
  boilingPoint: 77.36,
  density: 0.0012506,
  electronegativity: 3.04,
  atomicRadius: 155,
  ionizationEnergy: 1402.3,
  oxidationStates: [-3, -2, -1, 0, 1, 2, 3, 4, 5],
  valency: 3,
  maxBonds: 3,
  discoveredBy: 'Daniel Rutherford',
  yearDiscovered: 1772,
  isRadioactive: false,
  halfLife: null,
  color: '#4ECDC4',
  summary: 'Nitrogen makes up 78% of Earth\'s atmosphere.',
}

export const mockSodium: Element = {
  _id: 'na-id',
  id: 'Na',
  atomicNumber: 11,
  symbol: 'Na',
  name: 'Sodium',
  atomicMass: 22.990,
  category: 'alkali-metal',
  group: 1,
  period: 3,
  block: 's',
  electronConfiguration: '1s2 2s2 2p6 3s1',
  electronsPerShell: [2, 8, 1],
  phase: 'solid',
  meltingPoint: 370.87,
  boilingPoint: 1156,
  density: 0.971,
  electronegativity: 0.93,
  atomicRadius: 227,
  ionizationEnergy: 495.8,
  oxidationStates: [-1, 1],
  valency: 1,
  maxBonds: 1,
  discoveredBy: 'Humphry Davy',
  yearDiscovered: 1807,
  isRadioactive: false,
  halfLife: null,
  color: '#F38181',
  summary: 'Sodium is an alkali metal.',
}

export const mockChlorine: Element = {
  _id: 'cl-id',
  id: 'Cl',
  atomicNumber: 17,
  symbol: 'Cl',
  name: 'Chlorine',
  atomicMass: 35.453,
  category: 'halogen',
  group: 17,
  period: 3,
  block: 'p',
  electronConfiguration: '1s2 2s2 2p6 3s2 3p5',
  electronsPerShell: [2, 8, 7],
  phase: 'gas',
  meltingPoint: 171.6,
  boilingPoint: 239.11,
  density: 0.003214,
  electronegativity: 3.16,
  atomicRadius: 175,
  ionizationEnergy: 1251.2,
  oxidationStates: [-1, 1, 3, 5, 7],
  valency: 1,
  maxBonds: 1,
  discoveredBy: 'Carl Wilhelm Scheele',
  yearDiscovered: 1774,
  isRadioactive: false,
  halfLife: null,
  color: '#FF7675',
  summary: 'Chlorine is a halogen.',
}

export const mockIron: Element = {
  _id: 'fe-id',
  id: 'Fe',
  atomicNumber: 26,
  symbol: 'Fe',
  name: 'Iron',
  atomicMass: 55.845,
  category: 'transition-metal',
  group: 8,
  period: 4,
  block: 'd',
  electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d6',
  electronsPerShell: [2, 8, 14, 2],
  phase: 'solid',
  meltingPoint: 1811,
  boilingPoint: 3134,
  density: 7.874,
  electronegativity: 1.83,
  atomicRadius: 194,
  ionizationEnergy: 762.5,
  oxidationStates: [-2, -1, 0, 1, 2, 3, 4, 5, 6],
  valency: 3,
  maxBonds: 3,
  discoveredBy: 'Ancient',
  yearDiscovered: null,
  isRadioactive: false,
  halfLife: null,
  color: '#A29BFE',
  summary: 'Iron is the most common element on Earth.',
}

export const mockHelium: Element = {
  _id: 'he-id',
  id: 'He',
  atomicNumber: 2,
  symbol: 'He',
  name: 'Helium',
  atomicMass: 4.003,
  category: 'noble-gas',
  group: 18,
  period: 1,
  block: 's',
  electronConfiguration: '1s2',
  electronsPerShell: [2],
  phase: 'gas',
  meltingPoint: 0.95,
  boilingPoint: 4.22,
  density: 0.0001785,
  electronegativity: null,
  atomicRadius: 140,
  ionizationEnergy: 2372.3,
  oxidationStates: [0],
  valency: 0,
  maxBonds: 0,
  discoveredBy: 'Pierre Janssen',
  yearDiscovered: 1868,
  isRadioactive: false,
  halfLife: null,
  color: '#95E1D3',
  summary: 'Helium is a noble gas.',
}

// Mock Bonds
export const createMockBond = (
  id: string,
  fromId: string,
  toId: string,
  type: BondType = 'single'
): Bond => ({
  id,
  fromElementId: fromId,
  toElementId: toId,
  bondType: type,
})

// Mock Canvas Elements
export const createMockCanvasElement = (
  element: Element,
  position: { x: number; y: number },
  instanceId?: string
) => ({
  id: instanceId || `${element.symbol}-${Date.now()}`,
  elementId: element._id || element.symbol,
  symbol: element.symbol,
  count: 1,
  position,
  element,
})
